

## 개요
* 객체생성
* 색인 (정수, 슬라이스, 불리언, 팬시)
* 유니버셜 함수


In [1]:
#객체생성
import numpy as np
a1 = np.array([1,2,3])
a2 = np.array([[1,2,3],[4,5,6]])

In [15]:
#정수색인
print(f'a1[1]:{a1[1]}')
print(f'a2[1]:{a2[1]}')

a1[1]:2
a2[1]:[4 5 6]


In [3]:
#슬라이스색인
print(f'a1[1:]:{a1[1:]}\n, a2[:,1:]:{a2[:,1:]}')

a1[1:]:[2 3]
, a2[:,1:]:[[2 3]
 [5 6]]


In [4]:
#불리언색인
print(f'a1[a1<3]:{a1[a1<3]}, a2[a2<3]:{a2[a2<3]}')

a1[a1<3]:[1 2], a2[a2<3]:[1 2]


In [14]:
#팬시색인
print(f'a1[[2,0]]:{a1[[2,0]]}')
print(f'a2[[1,0],[1,2]]:{a2[[1,0],[1,2]]}')

a1[[2,0]]:[3 1]
a2[[1,0],[1,2]]:[5 3]


### 유니버셜 함수
* 1차원 : 증가하는 방향 (axis=0)
* 2차원 : 행 증가하는 방향 (axis=0), 열 증가하는 방향(axis=1)
* 브로드캐스팅    

In [ ]:
a2.sum(0) # 행증가하는 방향 : 열 병합

In [ ]:
a2.sum(1) # 열증가하는 방향 : 행 병합


## matrix  array 비교

In [16]:
from numpy import matrix, array
m1 = matrix([1,2,3])
a1 = array([1,2,3])

In [17]:
m1.shape

(1, 3)

In [18]:
m1.T

matrix([[1],
        [2],
        [3]])

In [19]:
a1.shape

(3,)

In [20]:
a1.T

array([1, 2, 3])


# numpy 이용 로또 번호 추출기

In [22]:
from numpy.random import permutation
permutation(45) + 1 # 1부터 45까지 # 로또 1부터 45까지이므로

array([33,  5, 35, 40, 20,  2, 17, 25, 30, 31, 39, 13, 16, 38, 18, 36, 24,
       10,  6,  7, 14, 32,  3, 45, 21, 28, 44,  4, 11, 12, 27, 15, 29,  9,
       37, 23,  1, 42, 41, 22, 43, 26, 34,  8, 19])

In [23]:
(permutation(45)+1)[:6] #45개중에서 6개만 추출

array([43, 40, 16, 13, 29, 33])

In [24]:
for _ in range(10):
    print((permutation(45)+1)[:6])

[45 14 38  4 20 32]
[32 29 36 12 19 30]
[45 39 37 31 33 25]
[27  6 17 45 21 39]
[ 2 30 24 41 25 45]
[28 35  2  8 19  3]
[38  2 15  7 24 22]
[ 5 42 36 13  8  1]
[ 5 28  3  1 32 24]
[27 19 28 39 15 32]


In [28]:
(np.random.randint(1, 45))[:6]

TypeError: 'int' object is not subscriptable